export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const FILL_ARRAY_CHOOSE_MENU = 'FILL_ARRAY_CHOOSE_MENU'
export const CLEAR_ARRAY_CHOOSE_MENU = 'CLEAR_ARRAY_CHOOSE_MENU'

export const SELECT_WEIGHT_PRODUCT = 'SELECT_WEIGHT_PRODUCT'
export const SELECT_QUANTITY_PRODUCT = 'SELECT_QUANTITY_PRODUCT'

export const PRODUCT_ADDED_TO_ORDER_LIST = 'PRODUCT_ADDED_TO_ORDER_LIST'
export const UPDATE_COUNT_AND_TOTAL_ORDER = 'UPDATE_COUNT_AND_TOTAL_ORDER'
export const PRODUCT_REMOVED_FROM_ORDER_LIST = 'PRODUCT_REMOVED_FROM_ORDER_LIST'
export const ALL_PRODUCTS_REMOVED_FROM_ORDER_LIST = 'ALL_PRODUCTS_REMOVED_FROM_ORDER_LIST'

